name: Qodana
on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main
            - dev
jobs:
    qodana:
        runs-on: alpine
        permissions:
            contents: write
            pull-requests: write
            checks: write
        steps:
            - uses: https://gitea.com/actions/checkout@v3
              with:
                  ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
                  fetch-depth: 0  # a full history is required for pull request analysis
            - name: 'Qodana Scan'
              uses: https://git.starair.ltd/mirror/qodana-action@v2024.3
              with:
                  args: --linter,jetbrains/qodana-js:2024.3
              env:
                  QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}