on:
  push:
    branches:
      - main
      - dev
  pull_request:
      types: [opened, synchronize, reopened]

name: SonarQube Scan
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-22.04
    steps:
    - name: Checking out
      uses: https://gitea.com/actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      run: |
        # 创建源列表目录
        mkdir -p /etc/apt/keyrings
        
        # 导入所有必需的 Debian 密钥
        gpg --no-default-keyring \
            --keyring /etc/apt/keyrings/debian-archive-keyring.gpg \
            --keyserver keyserver.ubuntu.com \
            --recv-keys 648ACFD622F3D138 0E98404D386FA1D9 112695A0E562B32A 54404762BBB6E853
            
        # 配置 Debian 源
        echo "deb [signed-by=/etc/apt/keyrings/debian-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main" | tee /etc/apt/sources.list
        echo "deb [signed-by=/etc/apt/keyrings/debian-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main" | tee -a /etc/apt/sources.list
        echo "deb [signed-by=/etc/apt/keyrings/debian-archive-keyring.gpg] https://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main" | tee -a /etc/apt/sources.list
        
        # 更新并安装
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-17-jdk
        
        # 验证安装
        java -version
        echo "JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64" >> $GITHUB_ENV
        export PATH=$JAVA_HOME/bin:$PATH       

    - name: Install SonarScanner
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
        export PATH=$JAVA_HOME/bin:$PATH
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
        echo "sonar.java.jdkHome=/usr/lib/jvm/java-17-openjdk-amd64" >> /opt/sonar-scanner/conf/sonar-scanner.properties

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
      run: |
        npm run test:coverage
        /opt/sonar-scanner/bin/sonar-scanner -X \
          -Dsonar.projectKey=node-back-end \
          -Dsonar.projectName=node-back-end \
          -Dsonar.sources=src \
          -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }} \
          -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.java.home=/usr/lib/jvm/java-17-openjdk-amd64 \
          -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
          -Dsonar.exclusions=**/node_modules/**,**/*.test.ts